export const data = [
    {
        "brand": "BYD",
        "y1": 30,
        "x1": 0.4,
        "y2": 66,
        "x2": 1.85,
        "japanese": "no",
        "arrow": "yes",
        "labelX": 0.5, 
        "labelY": 50
    },
    {
        "brand": "",
        "y1": 5,
        "x1": 2.25,
        "y2": 27,
        "x2": 2.6,
        "japanese": "no",
        "arrow": "no",
        "labelX": 2.5, 
        "labelY": 29
    },
    {
        "brand": "",
        "y1": 3.9,
        "x1": 2.1,
        "y2": 25.5,
        "x2": 2.3,
        "japanese": "no",
        "arrow": "no",
        "labelX": 1.25, 
        "labelY": 25
    },
    {
        "brand": "",
        "y1": 3.9,
        "x1": 3,
        "y2": 22,
        "x2": 2.6,
        "japanese": "no",
        "arrow": "no",
    },
    {
        "brand": "",
        "y1": 3.8,
        "x1": 2.5,
        "y2": 12.5,
        "x2": 2.48,
        "japanese": "no",
        "arrow": "no",
    },
    {
        "brand": "",
        "y1": 2.9,
        "x1": 3.3,
        "y2": 10,
        "x2": 2.55,
        "japanese": "no",
        "arrow": "no",
    },
    {
        "brand": "",
        "y1": 4,
        "x1": 2.2,
        "y2": 15.5,
        "x2": 2.4,
        "japanese": "no",
        "arrow": "no",
    },
    {
        "brand": "",
        "y1": 2.3,
        "x1": 2.8,
        "y2": 9.8,
        "x2": 3.1,
        "japanese": "no",
        "arrow": "no",
    },
    {
        "brand": "Volkswagen",
        "y1": 1,
        "x1": 10.8,
        "y2": 10,
        "x2": 8.2,
        "japanese": "no",
        "arrow": "no",
        "labelX": 8.1, 
        "labelY": 12
    },
    {
        "brand": "Toyota",
        "y1": 0.5,
        "x1": 9,
        "y2": 1.4,
        "x2": 8.6,
        "japanese": "yes",
        "arrow": "yes",
        "labelX": 8.1, 
        "labelY": 3.5
    },
    {
        "brand": "GM",
        "y1": 1.5,
        "x1": 8.4,
        "y2": 5,
        "x2": 6,
        "japanese": "no",
        "arrow": "no",
        "labelX": 5.35, 
        "labelY": 4
    },
    {
        "brand": "SAIC",
        "y1": 2.4,
        "x1": 7,
        "y2": 14,
        "x2": 5.5,
        "japanese": "no",
        "arrow": "no",
        "labelX": 5.2, 
        "labelY": 16
    },
    {
        "brand": "Hyundai",
        "y1": 0.6,
        "x1": 4.5,
        "y2": 9,
        "x2": 4,
        "japanese": "no",
        "arrow": "no",
        "labelX": 3.9, 
        "labelY": 11
    },
    {
        "brand": "",
        "y1": 0.2,
        "x1": 6,
        "y2": 4,
        "x2": 4.3,
        "japanese": "no",
        "arrow": "no"
    },
    {
        "brand": "",
        "y1": 2,
        "x1": 3.9,
        "y2": 7,
        "x2": 2.2,
        "japanese": "no",
        "arrow": "no"
    },
    {
        "brand": "Honda",
        "y1": 0.5,
        "x1": 3.8,
        "y2": 1.6,
        "x2": 2.3,
        "japanese": "yes",
        "arrow": "yes",
        "labelX": 2, 
        "labelY": -2
    },
    {
        "brand": "Nissan",
        "y1": 2.6,
        "x1": 4.2,
        "y2": 5,
        "x2": 2.25,
        "japanese": "yes",
        "arrow": "yes",
        "labelX": 2.1, 
        "labelY": 7
    },
    {
        "brand": "Suzuki",
        "y1": 0.3,
        "x1": 3.4,
        "y2": 0.3,
        "x2": 3.2,
        "japanese": "yes",
        "arrow": "yes",
        "labelX": 3.16, 
        "labelY": -3.4
    },
    {
        "brand": "Mitsubishi",
        "y1": 3,
        "x1": 1.5,
        "y2": 5,
        "x2": 1.16,
        "japanese": "yes",
        "arrow": "yes",
        "labelX": 0.3, 
        "labelY": 7
    },
    {
        "brand": "Subaru",
        "y1": 0.3,
        "x1": 1.6,
        "y2": 2.4,
        "x2": 1.2,
        "japanese": "yes",
        "arrow": "yes",
        "labelX": -0.2, 
        "labelY": 1
    },
    {
        "brand": "Mazda",
        "y1": 0.4,
        "x1": 1.2,
        "y2": 0.7,
        "x2": 1,
        "japanese": "yes",
        "arrow": "yes",
        "labelX": 0.6, 
        "labelY": -3
    },
];